import Trending from "@/features/movies/Trending";
import MostPopular from "@/features/movies/MostPopular";
import Head from "next/head";

const containerStyle = { width: "90%", margin: "auto" };

export default function Home() {
  return (
    <>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={containerStyle}>
        <Trending/>
        <MostPopular/>
      </main>
    </>
  );
}
